### ISSUE TITLE
ADS: Potential bug?

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTDESSERT#249]
Had an secondary error on the Hudle due to ad not showing. It's trying to load a scene called "-1" due to this code:

```
        GameStateManager.levelsSinceAd = GameStateManager.instance.levelsBeforeAd - 1;
                GameObject.Find ("Scripts").GetComponent<UIManager> ().SwitchScene (GameStateManager.sceneAfterAds);
```

Could this cause problem on iOS if an advert isn't ready?

**Comment by Laura-O4S** [comment]
Change #if UNITY_IOS -to- UNITY_ANDROID in UIManager - lines: 411, 439
